# This Template builds a function app project, validates by running unit tests and publishes the code coverage.


parameters:
  - name: jobname
    type: string
    default: 'ValidateFunctionApp'
  - name: dependsOn
    type: object
    default: []
  - name: workingDirectory
  - name: projectName
  - name: projects
    type: object
    default: []
  - name: dotNetSdkVersion
    type: string
  - name: privateNugetFeedName
    type: string
    default: 'Azure-Integration/Azure-Integration-Pacakages'

jobs:
  - job: ${{ parameters.jobName }}
    dependsOn: ${{ parameters.dependsOn }}
    
    steps:
      - checkout: self
        clean: true

      - task: UseDotNet@2
        name: 'InstallDotNetSdk'
        displayName: 'Install the .Net Core sdk'
        inputs:
          packageType: 'sdk'
          version: ${{ parameters.dotNetSdkVersion }}

      - task: NuGetToolInstaller@1
        displayName: 'Installing the nuget packages'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '**/function-apps/*.csproj'
          feedsToUse: 'select'
          vstsFeed: 'f72ed39b-6772-436c-8214-d88f23e69f0a'
